TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE places CASCADE;
TRUNCATE TABLE events CASCADE;

ALTER SEQUENCE user_id_seq RESTART WITH 1;
ALTER SEQUENCE places_id_seq RESTART WITH 1;
ALTER SEQUENCE event_id_seq RESTART WITH 1;