rest:
  kudago:
    url: https://kudago.com/public-api/v1.4
    read-timeout: 120s
    connect-timeout: 120s
    maximum-number-concurrent-requests: 5
  spring-app-currency:
    url: ${REST_CURRENCY_URL:http://localhost:8080/currency}
    read-timeout: 120s
    connect-timeout: 120s

fixed:
  thread:
    pool:
      size: 10

scheduled:
  thread:
    pool:
      size: 2

initialization:
  interval: PT1H

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fj
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: liquibase/changelog.xml

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        test:
          timer:
            histogram: true

jwt:
  secret-key: ${JWT_SECRET_KEY:FEAA575643235CF7B954951CC2D9EC14178D373DA120612792DBC905062CD0D8}
verification:
  code: ${VERIFICATION_CODE:0000}